### PR TITLE
feat: Added implementation for factors 

### PR DESCRIPTION
**Pull request by SpiderMath**
This pull request aims to add the implementation to get the factors of a given number. Here's the link to the specific TheAlgorithms [entry](https://the-algorithms.com/algorithm/factors)

### CODE REVIEW

**Comment by SpiderMath** [comment]
@siriak @imp2002 hey, you people there?

**Comment by SpiderMath** [comment]
It passes all the required checks, yet its been 5 whole days :frowning:

**Review by imp2002 — APPROVED** [review]

**Comment by SpiderMath** [comment]
image

It seems as if some code, which hasn't been authored by me, is failing the automated tests. What am I to do here? Quite confused here.

**Comment by imp2002** [comment]
> It seems as if some code, which hasn't been authored by me, is failing the automated tests. What am I to do here? Quite confused here.

I'm fix it in #432, just wait the PR been merged.

**Pull request merged**
