### PR TITLE
Rename insertion.rs to insertion_sort.rs

### PR DESCRIPTION
**Pull request by yanglbme**
See https://github.com/TheAlgorithms/Rust/blob/master/src/sorting/insertion_sort.rs

### CODE REVIEW

**Comment by yanglbme** [comment]
@AnshulMalik Please review, thanks.

**Comment by AnshulMalik** [comment]
It says conflicting files, can you please resolve the conflicts?

**Comment by yanglbme** [comment]
@AnshulMalik OK, I'll raise a new PR.

**Comment by yanglbme** [comment]
@AnshulMalik see #74

**Pull request closed without merging**
