### PR TITLE
Add `B-Tree` Implementation

### PR DESCRIPTION
**Pull request by Shub1427**
Reference: https://github.com/TheAlgorithms/Rust/issues/3

This PR focuses on implementing 3 specific BTree operations:
* Traverse
* Search
* Insert

> **PS:** Any code improvement suggestions are welcome.

### CODE REVIEW

**Comment by AnshulMalik** [comment]
This looks good, just delete seems to be missing.

**Comment by Shub1427** [comment]
Delete is a really tough one to understand. For people (beginners like me), it would be great if you fiddle with already existing BTree implementations and understand how Rotation/Merging works, with dummy data

**Comment by AnshulMalik** [comment]
Right, delete is tricky
Let's have different PR for the delete functionality.

**Comment by Shub1427** [comment]
Cool @AnshulMalik ! Have removed my last commit. Will raise it as a separate PR.

**Pull request merged**
