### PR TITLE
Bugfix/directory workflow

### PR DESCRIPTION
**Pull request by CSRessel**
# Pull Request Template

## Description

This PR attempts to address the problem of the directory workflow not writing back the repo.

The full discussion is here:  https://github.com/TheAlgorithms/Rust/issues/591

Before merging, @siriak should try:

1. adding a [personal access token](https://github.com/settings/tokens) to the repo secrets as `BOT_TOKEN` (classic is easiest, but if you do `fine-grained` make sure to give it `repo` permission)
2. make sure that for the `master` branch protection, his own account is included in the [Allow specific actors to bypass pull request requirements](https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/) list

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] I ran bellow commands using the latest version of **rust nightly**.
- [X] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [X] I ran `cargo fmt` just before my last commit.
- [X] I ran `cargo test` just before my last commit and all tests passed.
- [X] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [X] I added my algorithm to `DIRECTORY.md` with the correct link.
- [X] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

Please make sure that if there is a test that takes too long to run ( > 300ms), you `#[ignore]` that or
try to optimize your code or make the test easier to run. We have this rule because we have hundreds of
tests to run; If each one of them took 300ms, we would have to wait for a long time.

### CODE REVIEW

**Comment by siriak** [comment]
Could you clarify a few thing for me?
1. When adding a fine-grained access token, I only see my personal repos. I don't see TheAlgorithms repos. Do you know how to create a token for them?
image
2. Why does it need access to `master`? I'd expect it to commit to the feature branch so that changes to DIRECTORY.md can be reviewed too. Can we do it like that?

**Comment by siriak** [comment]
1. Getting PAT from account owner of TheAlgorithms is a profoundly complicated task to say the least, so I'd like to circumvent that if possible
2. That's insightful. `encouraging contributors to enable the GitHub Actions in their fork` is not an option in my opinion, we just can't encourage a significant number of people do that.
3. I'm fine with any approach you choose (either update in master or in PR) as long as it works and is not terribly complicated :)

Thanks for your effort, I really appreciate that!

**Comment by siriak** [comment]
P.S. see [this comment](https://github.com/orgs/community/discussions/13836#discussioncomment-7133341). It seems that there may be an issue with the currently proposed approach.

**Comment by siriak** [comment]
I will try doing this next weekend, I'm a little busy till then. Thank you!

**Comment by siriak** [comment]
Basically what these deploy keys do is they allow pushing to master. I have just allowed pushing to it (in branch protection settings). This allows a little bit more than I need, but I feel like it's way simpler than maintaining these deploy keys in the future should anything change. Could you resolve the conflicts, and then I'll merge to see how it works?

**Comment by CSRessel** [comment]
Just updated merge deps. Wanted to ask how you added the ssh key? Is it a secret for the repo (in which case I just need to add a couple lines to use something like the `web-factory/ssh-agent` workflow to setup the new ssh key), or is it something just inherited by all workflows and no explicit step there is needed?

I had anticipated needing some lines like:

```yaml
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DIRECTORY_DEPLOY_KEY }}
```

In order to explicitly use the elevated privileges with the deploy key.

**Comment by siriak** [comment]
I didn't add an ssh key. The workflow just uses some built-in authentication (I'm not terribly familiar with that)

**Review by siriak — APPROVED** [review]

**Comment by siriak** [comment]
Let's see it DIRECTORY is updated after I merge this PR

**Pull request merged**
