### PR TITLE
A new README.md

### PR DESCRIPTION
**Pull request by camilosampedro**
This Pull Request adresses #8 

It is based on the Python repository README.md. I specially looked for Python-specific references that could be changed to Rust in the document, and I consider that this is a very general algorithms README.

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Hey, we are going to have separate readme for the modules, so the sorting docs will go to sorting readme. 
So, we should just keep the headings here and the algorithms implemented and to be implemented.

**Comment by r0hit-gupta** [comment]
@AnshulMalik that is right. Let us have different README files for every different category. Can you please move these files to their appropriate directories? Thanks.

**Comment by camilosampedro** [comment]
I just updated it, separating it into different README.md files, in each of the directories.

**Comment by AnshulMalik** [comment]
We need to update the status of implemented algorithms as we progress.
Thanks @camilosampedro

**Pull request merged**
