### PR TITLE
Create postfix_evaluation.rs

### PR DESCRIPTION
**Pull request by cyrixninja**
# Pull Request Template

## Description
Simple Postfix Evaluation using Stack Implemented in Rust

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please replace `main` with automated tests

**Comment by cyrixninja** [comment]
> Please replace `main` with automated tests

Added Automated Tests

**Review by siriak — CHANGES_REQUESTED** [review]
Please remove `main`, everything else looks good

**Comment by cyrixninja** [comment]
> Please remove `main`, everything else looks good

Done 👍🏻

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
