### PR TITLE
Factorial, Combinations & Decimal_To_Fraction Functions 

### PR DESCRIPTION
**Pull request by octavianarmasu**
## Factorial
This Rust code provides implementations of the factorial calculation for positive integers, both iteratively and recursively. The code includes unit tests to ensure the correctness of the functions.

#### Iterative Factorial Calculation (`factorial` function)

The `factorial` function uses a straightforward iterative approach. It checks for base cases (0! and 1!) and, for other cases, calculates the factorial using the product of the range from 2 to the given number (inclusive). The `product` method is used to efficiently calculate the product of the range.

#### Recursive Factorial Calculation (`factorial_recursive` function)

The `factorial_recursive` function employs a recursive approach. It also checks for base cases and recursively calculates the factorial by multiplying the current number with the factorial of (n - 1). This recursive method provides a clear representation of the factorial definition.

## Combinations
Implemented a Rust version of the combinations function, which calculates the number of combinations of k elements from a set of n elements. The function now panics when provided with negative values for n or k, ensuring that only positive values are accepted.

- The combinations function follows the algorithm described in the [Wikipedia article on Combinations](https://en.wikipedia.org/wiki/Combination).
- Three unit tests are included to verify the correctness of the function for specific input values.

## Decimal to fraction
The decimal_to_fraction function in Rust converts decimal numbers to their simplest fraction form. It takes a floating-point number as input and returns a tuple representing the numerator and denominator of the simplified fraction.

- The function handles both integer and decimal input, ensuring that the output is in its simplest fraction form.
- If the input is already an integer, the function returns the integer and 1 as the denominator.
- For decimal input, it calculates the fractional part, determines the number of decimal places, and converts the decimal to an integer.
- Euclid's algorithm is then applied to find the greatest common divisor (GCD) of the numerator and denominator.
- The function reduces the fraction by dividing both the numerator and denominator by the GCD, providing the simplest form of the fraction.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] I ran bellow commands using the latest version of **rust nightly**.
- [X] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [X] I ran `cargo fmt` just before my last commit.
- [X] I ran `cargo test` just before my last commit and all tests passed.
- [X] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [X] I added my algorithm to `DIRECTORY.md` with the correct link.
- [X] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

### CODE REVIEW

**Review by siriak — COMMENTED** [review]
The factorial function is already implemented in this repository, could you merge it with your implementation?

**Comment by octavianarmasu** [comment]
Do you mean the fast_factorial function in the big_integer module?

**Comment by octavianarmasu** [comment]
~~Do you mean the fast_factorial function in the big_integer module?~~
I found it, it was in hello_bigmath.rs, I am going to merge it with my code.

**Comment by siriak** [comment]
Could you remove the factorial in hello_bigmath? It's duplicated there now

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
