### PR TITLE
Added License to the repository.

### LINKED ISSUE #103: License to the repository should be added.

### PR DESCRIPTION
**Pull request by walter-ind**
closes #103

### CODE REVIEW

**Comment by walter-ind** [comment]
@yanglbme please have a look at it.

**Comment by walter-ind** [comment]
> LGTM

means?

**Comment by yanglbme** [comment]
@AnshulMalik Travis CI reports `"Expected - Waiting for status to be reported"` on the GitHub Status API, but the status never arrives. See https://github.com/travis-ci/travis-ci/issues/10204 .

I'm not the owner of the Rust repository, so I have no rights to update the project's setting.

**Comment by yanglbme** [comment]
@walter-ind Look good to me :D

**Comment by walter-ind** [comment]
@AnshulMalik please have a look at it...

**Pull request merged**
