### PR TITLE
Add Morse Decoder.

### PR DESCRIPTION
**Pull request by aalekhpatel07**
## Feature

Add a function to decode a given string of Morse Code.

Signed-off-by: Aalekh Patel <aalekh.gwpeck.7998@icloud.com>

### CODE REVIEW

**Comment by imp2002** [comment]
thank you, but the CI has failed, please run `cargo fmt --all -- --check`, `cargo clippy --all -- -D warnings`, `cargo test`

**Comment by aalekhpatel07** [comment]
There! Clippy's happy now ;)

**Comment by imp2002** [comment]
thank you, i will review it a few hours later, have something to do.

**Review by siriak — APPROVED** [review]

**Review by imp2002 — DISMISSED** [review]

**Comment by imp2002** [comment]
hello, can help update the README?

**Comment by aalekhpatel07** [comment]
Readme has been updated.

**Review by imp2002 — APPROVED** [review]

**Pull request merged**
