### PR TITLE
Binary Search Tree

### PR DESCRIPTION
**Pull request by JarredAllen**
I coded a simple Binary Search Tree.

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Just need to run cargo fmt

**Comment by JarredAllen** [comment]
I have already run cargo fmt on this, and it gave a different output from what the one on the test does.

If it's relevant, I have rustfmt version 0.10.0, which is what it installed when I ran `cargo install rustfmt`, and I just ran `cargo fmt -- --force` to format it.

**Comment by AnshulMalik** [comment]
This is what the test script use: `rustup component add rustfmt-preview` may be we can try this once.

**Comment by JarredAllen** [comment]
I installed a newer version of rustfmt through rustup and ran it on the code and it made some changes from the older version. Apparently, installing it through cargo didn't get me the latest version. But it looks like everything is good now.

**Pull request merged**
