### PR TITLE
feat: Hinge Loss

### PR DESCRIPTION
**Pull request by mobley-trent**
# Pull Request Template

## Description

This PR is a sub task of issue #559 . It adds Hinge Loss algorithm under the Machine Learning directory.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [x] I added my algorithm to `DIRECTORY.md` with the correct link.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

Please make sure that if there is a test that takes too long to run ( > 300ms), you `#[ignore]` that or
try to optimize your code or make the test easier to run. We have this rule because we have hundreds of
tests to run; If each one of them took 300ms, we would have to wait for a long time.

### CODE REVIEW

**Comment by siriak** [comment]
Please fix `cargo clippy`. See how it's handled in other files

**Comment by mobley-trent** [comment]
Hello @siriak , it seems that I can only fix cargo clippy by adding `#[warn(dead_code)]` but I don't see this in the rest of the loss functions.

**Comment by siriak** [comment]
Please take a look at new errors. I think this may be because the name of module and function coincide, but it's just a guess. You should be able to fix this without `#[warn(dead_code)]`

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
