### PR TITLE
Update reverse.rs

### PR DESCRIPTION
**Pull request by dev-priyanshu15**
1. macro_rules! test_cases: This macro is designed to reduce repetition by defining multiple test cases at once. It takes a list of test names and test case tuples ((input, expected)).
2. $name:ident: The test function name. For example, test_simple_palindrome is generated as the test function name.
3. $test_case:expr: This represents a tuple of (input, expected) for each test.
4. Generated Test Functions: Each entry inside test_cases! expands into a separate test function. For example, the test_simple_palindrome macro expands into a function that tests if reversing "racecar" returns "racecar"

# Pull Request Template

## Description

Please include a summary of the change and which issue (if any) is fixed.
A brief description of the algorithm and your implementation method can be helpful too. If the implemented method/algorithm is not so
well-known, it would be helpful to add a link to an article explaining it with more details.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [x] I added my algorithm to `DIRECTORY.md` with the correct link.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

Please make sure that if there is a test that takes too long to run ( > 300ms), you `#[ignore]` that or
try to optimize your code or make the test easier to run. We have this rule because we have hundreds of
tests to run; If each one of them took 300ms, we would have to wait for a long time.

### CODE REVIEW

**Comment by dev-priyanshu15** [comment]
dont forget to add hacktoberfest-accepted label

**Comment by sozelfist** [comment]
Please close these spammed PRs. Please take a look at the CONTRIBUTING guidelines. If something like this happens one more time, we would like to consider blocking you from the repo.
> Last but not least, we welcome contributors to contribute to developing the repo but not PR spammer just for Hacktoberfest events.

**Comment by sozelfist** [comment]
Please close this one too, #818.

**Comment by vil02** [comment]
@dev-priyanshu15: I do not see the purpose of this PR.

**Pull request closed without merging**
