### PR TITLE
performance_improvement of math::prime_check

### PR DESCRIPTION
**Pull request by fffzlfk**
Improved performance of math::prime_check using Optimized School Method.

### CODE REVIEW

**Comment by imp2002** [comment]
This can run more fast indeed, but it's not look like a radical optimization, more like a little trick. Anyway thanks your comtribute.

**Review by imp2002 — CHANGES_REQUESTED** [review]
This can run more fast indeed, but it's not look like a radical optimization, more like a little trick. Anyway thanks your comtribute.

**Review by siriak — APPROVED** [review]
@imp2002 why not include it? This version is faster and still pretty easy to understand

**Comment by imp2002** [comment]
Yes, this version is really faster. But i dont' think it's more easy to understood. It's a rule that all prime numbers are adjacent to a multiple of `6`, not all people know this. I think the most basic popular approach should be remained and this version add as a optimize function, though the method which is in the repo now is not basic.

**Comment by siriak** [comment]
@fffzlfk could you make it a separate method instead of modifying the existing one?

**Pull request closed without merging**
