### PR TITLE
Add Binary Exponentiation

### PR DESCRIPTION
**Pull request by caojoshua**
# Pull Request Template

## Description

Add binary exponentiation. See comments at top of source file for details. Or see https://cp-algorithms.com/algebra/binary-exp.html.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] I ran bellow commands using the latest version of **rust nightly**.
- [X] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [X] I ran `cargo fmt` just before my last commit.
- [X] I ran `cargo test` just before my last commit and all tests passed.
- [X] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

Please make sure that if there is a test that takes too long to run ( > 300ms), you `#[ignore]` that or
try to optimize your code or make the test easier to run. We have this rule because we have hundreds of
tests to run; If each one of them took 300ms, we would have to wait for a long time.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please run `cargo clippy`, everything else looks good

**Comment by caojoshua** [comment]
I went ahead and made the change suggested by clippy in the GitHub workflow. But my local clippy was not able to catch this. Do you know what I'm missing?

```
archlinux [~/src/thealgos/Rust]$ cargo clippy -V
clippy 0.1.72 (101fa90 2023-06-04)
archlinux [~/src/thealgos/Rust]$ cargo clippy --all -- -D warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
archlinux [~/src/thealgos/Rust]$ git diff
archlinux [~/src/thealgos/Rust]$
```

**Comment by siriak** [comment]
The clippy version is probably different, but I'm not sure which one we are using.

**Review by siriak — APPROVED** [review]

**Comment by siriak** [comment]
Thanks!

**Pull request merged**
