### PR TITLE
Move tests for bubble sort to match standard

### PR DESCRIPTION
**Pull request by horahh**
* Split test in two ascending and descending

### CODE REVIEW

**Comment by horahh** [comment]
can someone point me to where to look for the failure? I am not seeing any information about what the regression is? and in my machine cargo test is passing the 100 tests

**Comment by sandmor** [comment]
> The command "cargo fmt --all -- --check" exited with 1.

The PR fails by the format not by the test, to fix it just run `cargo fmt --all`

**Review by AnshulMalik — APPROVED** [review]
LGTM

**Comment by AnshulMalik** [comment]
Thanks @horahh

**Pull request merged**
