### PR TITLE
added Linear Interpolation by Timothy Kandiado

### PR DESCRIPTION
**Pull request by TimothyKandiado**
## Description

added linear interpolation and lagrange polynomial interpolation algorithms in the math directory

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ x ] I ran bellow commands using the latest version of **rust nightly**.
- [ x ] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [ x ] I ran `cargo fmt` just before my last commit.
- [ x ] I ran `cargo test` just before my last commit and all tests passed.
- [ x ] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

### CODE REVIEW

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by siriak** [comment]
Please run `cargo fmt`. Now it fails with
```
Diff in /home/runner/work/Rust/Rust/src/math/interpolation.rs at line 73:
         let defined_points = vec![(0.0, 0.0), (1.0, 1.0), (2.0, 4.0), (3.0, 9.0)];
 
         // check for equality
-        assert_eq!(
-            lagrange_polynomial_interpolation(1.0, &defined_points),
-            1.0
-        );
-        assert_eq!(
-            lagrange_polynomial_interpolation(2.0, &defined_points),
-            4.0
-        );
-        assert_eq!(
-            lagrange_polynomial_interpolation(3.0, &defined_points),
-            [9](https://github.com/TheAlgorithms/Rust/actions/runs/5058758579/jobs/9079526049?pr=500#step:3:10).0
-        );
+        assert_eq!(lagrange_polynomial_interpolation(1.0, &defined_points), 1.0);
+        assert_eq!(lagrange_polynomial_interpolation(2.0, &defined_points), 4.0);
+        assert_eq!(lagrange_polynomial_interpolation(3.0, &defined_points), 9.0);
```

**Comment by TimothyKandiado** [comment]
I have run cargo fix again, please check if it works now.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
