### PR TITLE
Created moore_voting.rs

### PR DESCRIPTION
**Pull request by RuchNas-Pottah**
Added Moore's Voting Algorithm to find the majority element

# Pull Request Template

## Description

Added Moore's Voting Algorithm to find the majority element, along with commented description

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I ran bellow commands using the latest version of **rust nightly**.
- [ ] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [ ] I ran `cargo fmt` just before my last commit.
- [ ] I ran `cargo test` just before my last commit and all tests passed.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

Please make sure that if there is a test that takes too long to run ( > 300ms), you `#[ignore]` that or
try to optimize your code or make the test easier to run. We have this rule because we have hundreds of
tests to run; If each one of them took 300ms, we would have to wait for a long time.

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
The code looks good, could you please replace `main` with tests? And please pick a better place for it because it's not a search

**Comment by RuchNas-Pottah** [comment]
> The code looks good, could you please replace `main` with tests? And please pick a better place for it because it's not a search

Greetings!
I have placed it in the search folder as it searches for the majority element, and reports if there are none. Should I make further changes?

**Review by siriak — COMMENTED** [review]
Let's rename it to `moore_voting.rs` and put it in `src/searching` since I can't find a better place for it

**Comment by RuchNas-Pottah** [comment]
> Let's rename it to `moore_voting.rs` and put it in `src/searching` since I can't find a better place for it

I have made the changes

**Comment by RuchNas-Pottah** [comment]
> Looks good, thanks!

Yaay! Thanks for approving!

**Pull request merged**
