### PR TITLE
Add square root by Newtons method

### PR DESCRIPTION
**Pull request by fffzlfk**

### CODE REVIEW

**Comment by er888kh** [comment]
I'm not sure whether this is important or not, but big numbers might result in infinite loop (the error would never reach 1e-10 level in f64). It might be useful (or maybe not) to use a relative error threshold or a fixed number of iterations.

**Comment by ozkanpakdil** [comment]
out of curiosity, is this O(logN) ?

**Comment by er888kh** [comment]
> out of curiosity, is this O(logN) ?

Newton's method converges quadratically: when the approximation comes sufficiently close to the actual root, each time its difference with root is squared (assuming the method doesn't break or hit edge cases, which doesn't happen for finding square root of numbers but can happen in more complicated functions).

**Review by siriak — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
