### PR TITLE
added quicksort, bubblesort and related tests

### PR DESCRIPTION
**Pull request by yashwanthreddyg**

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Hey @yashwanthreddyg. Nice work there! Could you please rebase once.

**Comment by yashwanthreddyg** [comment]
@AnshulMalik  I don't see any merge conflicts.

**Comment by AnshulMalik** [comment]
Yeah, you are right, I added travis in between, it would not trigger a test for this PR, so a rebase might do the trick. :)

**Comment by AnshulMalik** [comment]
Thanks @yashwanthreddyg , hoping to see more from you :)

**Pull request merged**
