### PR TITLE
feat: added eulerian path to graph

### PR DESCRIPTION
**Pull request by jeevanpranav02**
## Description

Implementation of Eulerian Path from the issue [#344](https://github.com/TheAlgorithms/Rust/issues/344#issue-1292204555)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

I hope this closes the issue for Euclerian Path. 
I would request if you can add label:```hactoberfest-accepted``` to this PR if applicable. :)

### CODE REVIEW

**Comment by siriak** [comment]
Please check why `cargo clippy` fails

**Comment by jeevanpranav02** [comment]
I checked the warning, and when I ran ```cargo clippy --all -- -D warnings``` there  was no error on my PC. However, here, Clippy suggested a change, which I made. If there are any other changes you'd like me to make, please feel free to ask. I'll be happy to do it.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by jeevanpranav02** [comment]
Thanks @siriak Can you please add  label:```hactoberfest-accepted``` : )

**Pull request merged**
