### PR TITLE
Implement the elliptic curve group law

### PR DESCRIPTION
**Pull request by boxdot**
## Description

The implementation is done for a finite field of characteristic != 2, 3
and the curve of the form `y^2 = x^3 + Ax^2 + B`.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

### CODE REVIEW

**Comment by boxdot** [comment]
I am considering to split this PR into two: 

1. Add finite field of prime order implementation.
2. Add elliptic group law implementation based on 1.

What do you think?

**Comment by siriak** [comment]
Feel free to split this into 2 PRs. And could you implement Field in a separate file? So that it can be reused for other algorithms

**Comment by siriak** [comment]
Ping me when it's time to review

**Comment by boxdot** [comment]
> Ping me when it's time to review

The field trait and prime field implementation can be reviewed in #549

**Comment by boxdot** [comment]
Based on top of https://github.com/TheAlgorithms/Rust/pull/549. Waiting for the latter to be merged first.

**Comment by boxdot** [comment]
> Based on top of #549. Waiting for the latter to be reviewed first.

#549 is merged. Now this PR only contains the relevant changes.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
