### PR TITLE
Added Max Height of Stacking Cubes Problem

### PR DESCRIPTION
**Pull request by jeevanpranav02**
# Pull Request

## Description
Problem Link: [Maximum Height by Stacking Cubes](https://leetcode.com/problems/maximum-height-by-stacking-cuboids/description/)

## Type of change
Added a solution on a dynamic programming problem

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

Its my first time making a contribution...

Is this ok or should I change something in here. : )

### CODE REVIEW

**Review by siriak — COMMENTED** [review]
Hi, we don't add leetcode problems

**Comment by siriak** [comment]
We only add well-known algorithms

**Comment by jeevanpranav02** [comment]
Am sorry! Can you suggest me something that so that I can contribute : )

**Comment by siriak** [comment]
You can see open issues like https://github.com/TheAlgorithms/Rust/issues/344, but please check if the algorithm is already implemented and write a comment if so and I'll mark it as done

**Comment by jeevanpranav02** [comment]
Thanks @siriak I'll look in it.

**Comment by jeevanpranav02** [comment]
Hi @siriak Most of those issues are almost completed... 
Can I implement *Hashing* using these techniques...
- LINEAR PROBING
- QUADRATIC PROBING
- SEPARATE CHAINING TECHNIQUE
- DOUBLE HASHING TECHNIQUE

**Comment by jeevanpranav02** [comment]
Sorry to bother you @siriak : ) Can I try Eulerian Path? Its not implemented yet.

**Pull request closed without merging**
