### PR TITLE
Added Miller Rabin primality test

### PR DESCRIPTION
**Pull request by er888kh**
Added [Miller Rabin](https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test) test.

I was wondering if some graph algorithms should be added. I think we are missing quite a few important and useful algorithms (all pairs shortest path, bipartite matching, max flow, ...). What do you think should be implemented first (graph or otherwise)?

### CODE REVIEW

**Comment by imp2002** [comment]
run `cargo clippy` and update branch thanks.👀

**Comment by er888kh** [comment]
Oops, my bad. I'm new to rust ecosystem.

**Review by siriak — CHANGES_REQUESTED** [review]
Please fix failing checks, thanks!

**Comment by er888kh** [comment]
> Please fix failing checks, thanks!

It seems like the clippy ones are not related to my commit:
- `src/ciphers/morse_code.rs:22:60`
- `src/ciphers/polybius.rs:81:18`
- `src/string/manacher.rs:75:20`

Maybe because other files are older in my fork? I'm not sure.
Let me see if I can fix this.

**Comment by siriak** [comment]
I see, but could you fix them in this or in a different PR? I'd be really thankful. If not, I'll merge as-is.

**Comment by er888kh** [comment]
> I see, but could you fix them in this or in a different PR? I'd be really thankful. If not, I'll merge as-is.

Yeah sure. I will create a new PR and fix the issue.

**Comment by er888kh** [comment]
> I see, but could you fix them in this or in a different PR? I'd be really thankful. If not, I'll merge as-is.

The problem was solved in #283.

**Review by siriak — APPROVED** [review]

**Pull request merged**
