### PR TITLE
Clippy

### PR DESCRIPTION
**Pull request by qsantos**
## Description

I'd like to contribute the A* algorithm to the project, but I noticed many clippy warnings. This PR addresses most of them, and ignores 2. You can look commit by commit for each type of lint rule. I've seen that there is [a workflow](https://github.com/TheAlgorithms/Rust/actions/runs/4362844991/jobs/7628222154) running `cargo clippy`, but maybe it's using an older version?

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warning` just before my last commit and fixed any issue that was found. (**NOTE:** it's `warnings` with an s (as in the CONTRIBUTING.md), `--all` looks obsolete)
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines. (**NOTE:** it's `CONTRIBUTING.md`)

### CODE REVIEW

**Review by siriak — COMMENTED** [review]
Good job! What does it suggest writing instead of needless range loops? I'd rather we fixed it

**Comment by siriak** [comment]
And could you also check which version of clippy is used locally and in the CI workflow? Unfortunately, I'm unable to find it. The CI check so far passes even without your fixes

**Comment by siriak** [comment]
And as for the PR description, I've added s to warning, but --all flag seems to be relevant. Please correct me if I'm wrong

**Comment by qsantos** [comment]
> Good job! What does it suggest writing instead of needless range loops? I'd rather we fixed it

I think it's fine to sometimes tell Clippy that it's really easier to just use indices. For the first one, maybe unrolling the loop would be nicer. For the second one, I think we should just silence the warning.

# First One

## Original

```rust
        let len = 16;
        let mut adj: Vec<Vec<usize>> = vec![vec![]; len];
        adj[1].push(2);
        adj[15].push(14);
        for i in 2..15 {
            adj[i].push(i + 1);
            adj[i].push(i - 1);
        }
        let mut cd = CentroidDecomposition::new(len - 1);
```

## Just applying enumerate

```rust
        let len = 16;
        let mut adj: Vec<Vec<usize>> = vec![vec![]; len];
        adj[1].push(2);
        adj[15].push(14);
        for (i, adj_cell) in adj[2..15].iter_mut().enumerate() {
            adj_cell.push(i + 3);
            adj_cell.push(i + 1);
        }
        let mut cd = CentroidDecomposition::new(len - 1);
```

It's very hard to see the relation between `i` and the position in the vector being filled.

# Keeping the same values for i

```rust
        let len = 16;
        let mut adj: Vec<Vec<usize>> = vec![vec![]; len];
        adj[1].push(2);
        adj[15].push(14);
        for (i, adj_cell) in adj.iter_mut().enumerate().skip(2).take(13) {
            adj_cell.push(i + 1);
            adj_cell.push(i - 1);
        }
        let mut cd = CentroidDecomposition::new(len - 1);
```

Slightly better, but we still don't see the index.

## Incremental initialization

At this point, we could just push to the Vec, avoiding the all `iter_mut().enumerate().skip(2).take(13)`:

```rust
        let len = 16;
        let mut adj: Vec<Vec<usize>> = Vec::new();
        adj.push(vec![]);
        adj.push(vec![2]);
        for i in 2..15 {
            adj.push(vec![i - 1, i + 1]);
        }
        adj.push(vec![14]);
        let mut cd = CentroidDecomposition::new(len - 1);
```

## Getting rid of mutations

There are not that many elements, so we could just list them explicitly. The nice thing is that we can get run of the `mut adj`.

```rust
        let adj: [Vec<usize>; 16] = [
            vec![],
            vec![2],
            vec![1, 3],
            vec![2, 4],
            vec![3, 5],
            vec![4, 6],
            vec![5, 7],
            vec![6, 8],
            vec![7, 9],
            vec![8, 10],
            vec![9, 11],
            vec![10, 12],
            vec![11, 13],
            vec![12, 14],
            vec![13, 15],
            vec![14],
        ];
        let mut cd = CentroidDecomposition::new(adj.len() - 1);
```

It's better, but the relation is still not as obvious as in the first version. However, we can more easily see the relations between the different nodes.

# Second One

## Original

```rust
        let mut adj: Vec<Vec<usize>> = vec![vec![]; n + 1];
        let mut parent: Vec<usize> = vec![0; n + 1];
        let mut hld = HeavyLightDecomposition::new(n);
        let mut lcg = LinearCongruenceGenerator::new(1103515245, 12345, 314);
        parent[2] = 1;
        adj[1].push(2);
        for i in 3..=n {
            // randomly determine the parent of each vertex.
            // There will be modulus bias, but it isn't important
            let par_max = i - 1;
            let par_min = (10 * par_max + 1) / 11;
            // Bring par_min closer to par_max to increase expected tree height
            let par = (lcg.next() as usize % (par_max - par_min + 1)) + par_min;
            adj[par].push(i);
            parent[i] = par;
        }
```

## Just applying enumerate

```rust
        let mut adj: Vec<Vec<usize>> = vec![vec![]; n + 1];
        let mut parent: Vec<usize> = vec![0; n + 1];
        let mut hld = HeavyLightDecomposition::new(n);
        let mut lcg = LinearCongruenceGenerator::new(1103515245, 12345, 314);
        parent[2] = 1;
        adj[1].push(2);
        for (i, parent_cell) in parent[3..=n].iter_mut().enumerate() {
            // randomly determine the parent of each vertex.
            // There will be modulus bias, but it isn't important
            let par_max = i + 2;
            let par_min = (10 * par_max + 1) / 11;
            // Bring par_min closer to par_max to increase expected tree height
            let par = (lcg.next() as usize % (par_max - par_min + 1)) + par_min;
            adj[par].push(i + 3);
            *parent_cell = par;
        }
```

I really do not like this one. There are still direct array accesses, but Clippy cannot see we're doing something hybrid.

## Keeping the same values for i

For comprehensiveness:

```rust
        let mut adj: Vec<Vec<usize>> = vec![vec![]; n + 1];
        let mut parent: Vec<usize> = vec![0; n + 1];
        let mut hld = HeavyLightDecomposition::new(n);
        let mut lcg = LinearCongruenceGenerator::new(1103515245, 12345, 314);
        parent[2] = 1;
        adj[1].push(2);
        for (i, parent_cell) in parent.iter_mut().enumerate().skip(3).take(n - 2) {
            // randomly determine the parent of each vertex.
            // There will be modulus bias, but it isn't important
            let par_max = i - 1;
            let par_min = (10 * par_max + 1) / 11;
            // Bring par_min closer to par_max to increase expected tree height
            let par = (lcg.next() as usize % (par_max - par_min + 1)) + par_min;
            adj[par].push(i);
            *parent_cell = par;
        }
```

## Others?

Considering the complex non-deterministic relationship between `parent` and `adj`, I think a “pure” version (using no indices) would be very hard to write and read.

**Comment by qsantos** [comment]
> And as for the PR description, I've added s to warning, but --all flag seems to be relevant. Please correct me if I'm wrong

Thanks! I have not found `--all` in `cargo help clippy`, nor in the official documentation. The [recommended use](https://github.com/rust-lang/rust-clippy#travis-ci) does not seem to include this option. I think this might have been made the default. But it does not hurt in any case.

**Comment by qsantos** [comment]
> And could you also check which version of clippy is used locally and in the CI workflow? Unfortunately, I'm unable to find it. The CI check so far passes even without your fixes

Local:

```
$ cargo version
cargo 1.70.0-nightly (7d3033d2e 2023-03-08)
```

The CI seems to be using `1.67.1`: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#rust-tools. Running `cargo +1.67.1 clippy --all -- -D warnings` indeed succeeds without any warnings.

**Review by siriak — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
