### PR TITLE
linked-list

### PR DESCRIPTION
**Pull request by chronos25**
linked list has length: 10
10->9-> 8-> 7-> 6->5-> 4-> 3-> 2-> 1-> Nil
where **Time complexity** of append is **O(n)** where n is the number of nodes in linked list. Since there is a loop from head to end, the function does O(n) work.

### CODE REVIEW

**Comment by AnshulMalik** [comment]
I like it @chronos25 . Let's make the list generic, so that it's not only valid for just numbers.

**Comment by AnshulMalik** [comment]
Hey @chronos25 any updates on this?

**Comment by chronos25** [comment]
no not now ! i'm working later on it.

**Comment by AnshulMalik** [comment]
Please feel free to open a new PR :)

**Pull request closed without merging**
