### PR TITLE
Added Z Algorithm

### PR DESCRIPTION
**Pull request by er888kh**

### CODE REVIEW

**Comment by er888kh** [comment]
> Please fix build with `cargo fmt` and `cargo clippy`, thanks!

I definitely ran `cargo clippy --all -- -D warnings` on my own machine, and it didn't find any errors (and still doesn't). Any idea why this is happening to my PRs?

**Comment by imp2002** [comment]
Click here you can see the detail.

image
image

**Comment by er888kh** [comment]
I did check details.
If you take a look, none of the issues are related to my commits:
- `morse_code.rs`
- `polybius.rs`
- `manacher.rs`

**Comment by imp2002** [comment]
Yeah, that's not your problem, sorry. Could you help fix the error part, or wait I fix it, then pull the update.

**Comment by er888kh** [comment]
I found the problem. I was on stable, which had no issue. I switched to nightly and now I get the same deprecation warnings.

**Comment by imp2002** [comment]
OK, thanks, i will change it to stable version.

**Review by siriak — APPROVED** [review]
Thanks!

**Pull request merged**
