### PR TITLE
Ternary Search Algorithm

### PR DESCRIPTION
**Pull request by mime8**
Added ternary search algorithm implementation.

### CODE REVIEW

**Comment by er888kh** [comment]
Can you add one function to each file, such that it takes a closure instead of a list? This way we can do so much more, e.g. find vertex of a parabola or calculate pi using trigonometric functions.

**Comment by mime8** [comment]
> Can you add one function to each file, such that it takes a closure instead of a list? This way we can do so much more, e.g. find vertex of a parabola or calculate pi using trigonometric functions.

Hi, @er888kh . Just to clarify, besides naive approach you also want a version of ternary algorithm for working with unimodal functions, correct?

**Comment by er888kh** [comment]
> Hi, @er888kh . Just to clarify, besides naive approach you also want a version of ternary algorithm for working with unimodal functions, correct?

Yes, that would be great (of course a few more parameters should be added by the user, like two points and some relative minimum acceptable error)

**Comment by mime8** [comment]
> > Hi, @er888kh . Just to clarify, besides naive approach you also want a version of ternary algorithm for working with unimodal functions, correct?
> 
> Yes, that would be great (of course a few more parameters should be added by the user, like two points and some relative minimum acceptable error)

There would be 2 functions actually. For minimum and maximum. Same goes for recursive option.
Any preference for types for start/end bounds? I was thinking about just using float.

**Comment by er888kh** [comment]
It would make sense to use f64

**Comment by mime8** [comment]
> It would make sense to use f64

Didn't see your reply and pushed my changes. Please, tell me if the new changes are what you wanted. I can switch types later.

**Comment by er888kh** [comment]
Don't worry, it's fine. Let's just wait and see if maintainers approve it.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
