### PR TITLE
MEX- Minimum Excluded Element

### PR DESCRIPTION
**Pull request by Arjun31415**
MEX algorithm using BTreeSet and array sorting

### CODE REVIEW

**Comment by Arjun31415** [comment]
How do i circumvent the `![feature(...)]` error on the stable branch ?

**Comment by Arjun31415** [comment]
ok fixed it for now with a slight hackish solution using `iter().next()`

**Comment by Arjun31415** [comment]
build is also fixed

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
